import assert from 'node:assert/strict'
import { spawnSync } from 'node:child_process'
import { cpSync, existsSync, mkdirSync, mkdtempSync, readFileSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import { test } from 'node:test'

const ROOT = resolve(import.meta.dirname, '..')
const FIXTURE = join(ROOT, 'test', 'fixtures', 'node-pnpm')
const scaffold = (target, ...extra) =>
  spawnSync(process.execPath, [join(ROOT, 'scripts', 'scaffold.mjs'), '--target', target, '--json', ...extra], { encoding: 'utf8' })
const validate = (target, ...extra) =>
  spawnSync(process.execPath, [join(ROOT, 'scripts', 'validate.mjs'), '--target', target, '--json', ...extra], { encoding: 'utf8' })

function fresh() {
  const dir = mkdtempSync(join(tmpdir(), 'harness-scaffold-'))
  cpSync(FIXTURE, dir, { recursive: true })
  return dir
}

test('scaffold writes the full set, detects pnpm + biome, and is idempotent', () => {
  const dir = fresh()
  const r = scaffold(dir)
  assert.equal(r.status, 0, r.stderr)
  const out = JSON.parse(r.stdout)
  const written = out.results.filter((x) => x.status === 'written').map((x) => x.path)
  assert.deepEqual(
    written.sort(),
    ['.agent/context.md', 'CLAUDE.md', 'claude-progress.md', 'docs/harness/clean-state-checklist.md', 'docs/harness/quality-document.md', 'docs/harness/session-handoff.md', 'feature_list.json', 'harness.json', 'init.sh'].sort(),
  )
  const d = JSON.parse(readFileSync(join(dir, 'harness.json'), 'utf8'))
  assert.equal(d.project, 'fixture')
  assert.equal(d.commands.install, 'pnpm install --frozen-lockfile')
  assert.equal(d.commands.format, 'pnpm exec biome check --write {file}')
  assert.equal(d.requires.node, '>=22')
  assert.ok(!existsSync(join(dir, 'docs/harness/evaluator-rubric.md')))
  assert.ok(readFileSync(join(dir, '.agent/context.md'), 'utf8').startsWith('<!-- GENERATED by /harness:init'))

  // second run: everything skipped or unchanged, nothing overwritten
  const again = JSON.parse(scaffold(dir).stdout)
  assert.ok(again.results.every((x) => x.status === 'skipped' || x.status === 'unchanged'), JSON.stringify(again.results))
})

test('scaffold appends a harness block to an existing CLAUDE.md and refreshes it in place', () => {
  const dir = fresh()
  writeFileSync(join(dir, 'CLAUDE.md'), '# My project\n\nHand-written rules.\n')
  const first = JSON.parse(scaffold(dir).stdout)
  assert.equal(first.results.find((x) => x.path === 'CLAUDE.md').status, 'block-appended')
  const md = readFileSync(join(dir, 'CLAUDE.md'), 'utf8')
  assert.match(md, /^# My project\n\nHand-written rules\./)
  assert.equal(md.match(/<!-- harness:start -->/g).length, 1)

  // tamper inside the block, run again with --force: block refreshed, prose untouched
  writeFileSync(join(dir, 'CLAUDE.md'), md.replace('End every working session', 'TAMPERED'))
  const second = JSON.parse(scaffold(dir, '--force').stdout)
  assert.equal(second.results.find((x) => x.path === 'CLAUDE.md').status, 'block-refreshed')
  const md2 = readFileSync(join(dir, 'CLAUDE.md'), 'utf8')
  assert.doesNotMatch(md2, /TAMPERED/)
  assert.match(md2, /Hand-written rules/)
  assert.equal(md2.match(/<!-- harness:start -->/g).length, 1)
})

test('scaffold never replaces a hand-written .agent/context.md without --force', () => {
  const dir = fresh()
  mkdirSync(join(dir, '.agent'), { recursive: true })
  writeFileSync(join(dir, '.agent', 'context.md'), '# mine\n')
  const r = JSON.parse(scaffold(dir).stdout)
  assert.equal(r.results.find((x) => x.path === '.agent/context.md').status, 'skipped')
  assert.equal(readFileSync(join(dir, '.agent', 'context.md'), 'utf8'), '# mine\n')
  const forced = JSON.parse(scaffold(dir, '--force').stdout)
  assert.equal(forced.results.find((x) => x.path === '.agent/context.md').status, 'regenerated')
})

test('validate scores a fresh scaffold and flags the example feature; a broken list fails', () => {
  const dir = fresh()
  scaffold(dir)
  const r = validate(dir)
  const out = JSON.parse(r.stdout)
  assert.ok(out.overall >= 70, `score ${out.overall}`)
  assert.ok(out.findings.some((f) => /example feature/.test(f.message)))
  assert.equal(r.status, 0, r.stdout)

  const fl = JSON.parse(readFileSync(join(dir, 'feature_list.json'), 'utf8'))
  fl.features[0].status = 'passing'
  writeFileSync(join(dir, 'feature_list.json'), JSON.stringify(fl))
  const bad = validate(dir)
  assert.equal(bad.status, 1)
  assert.ok(JSON.parse(bad.stdout).findings.some((f) => f.level === 'fail' && /evidence/.test(f.message)))
})

test('validate reports a missing harness as a fail with score 0', () => {
  const dir = mkdtempSync(join(tmpdir(), 'harness-none-'))
  const r = validate(dir)
  assert.equal(r.status, 1)
  assert.equal(JSON.parse(r.stdout).overall, 0)
})

test('init.sh template reads commands from harness.json and runs verify', () => {
  const dir = fresh()
  scaffold(dir, '--install', '', '--verify', 'echo VERIFIED', '--start', 'echo START', '--requires', '{"node":">=22"}')
  const r = spawnSync('bash', ['./init.sh'], { cwd: dir, encoding: 'utf8' })
  assert.equal(r.status, 0, r.stderr + r.stdout)
  assert.match(r.stdout, /Running baseline verification: echo VERIFIED/)
  assert.match(r.stdout, /VERIFIED/)
  assert.match(r.stdout, /echo START/)
  assert.match(r.stdout, /node \d+\.\d+\.\d+ ok \(>=22\)/)
  assert.doesNotMatch(r.stdout, /Syncing dependencies/)
})

test('init.sh fails the version gate when a required tool is missing', () => {
  const dir = fresh()
  scaffold(dir, '--install', '', '--verify', 'true', '--requires', '{"definitely-not-a-tool-xyz":">=1"}')
  const r = spawnSync('bash', ['./init.sh'], { cwd: dir, encoding: 'utf8' })
  assert.equal(r.status, 1)
  assert.match(r.stderr, /definitely-not-a-tool-xyz not found/)
})
